---
# File: tasks/install.yml - package installation tasks for openbao

- name: OpenBao Install || OS packages
  become: true
  ansible.builtin.package:
    name: "{{ openbao_os_packages }}"
    state: present
    update_cache: true
  tags: installation
  when: (openbao_os_packages is defined) and (openbao_os_packages | length > 0)

- name: OpenBao Install || Check OpenBao package file (local)
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ openbao_pkg }}"
  become: false
  run_once: true
  register: openbao_package
  delegate_to: 127.0.0.1

- name: "OpenBao Install || Download OpenBao (local) → {{ openbao_archive_url }}"
  ansible.builtin.get_url:
    url: "{{ openbao_archive_url }}"
    dest: "{{ role_path }}/files/{{ openbao_pkg }}"
    timeout: "60"
    mode: "0644"
  become: "{{ openbao_privileged_install }}"
  run_once: true
  tags: installation
  when: not openbao_package.stat.exists | bool
  delegate_to: 127.0.0.1

- name: OpenBao Install || Unarchive OpenBao (local)
  ansible.builtin.unarchive:
    src: "{{ role_path }}/files/{{ openbao_pkg }}"
    dest: "{{ role_path }}/files/"
    creates: "{{ role_path }}/files/openbao"
  become: "{{ openbao_privileged_install }}"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1

- name: OpenBao Install || Install OpenBao
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/openbao"
    dest: "{{ openbao_bin_path }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0755"
  notify: Restart openbao
  tags: installation

- name: OpenBao Install || Cleanup (local)
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  become: "{{ openbao_privileged_install }}"
  with_fileglob: "{{ role_path }}/files/openbao"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1
