---
# handlers file for openbao

- name: Restart openbao
  become: true
  ansible.builtin.service:
    name: '{{ openbao_systemd_service_name }}'
    state: restarted
  when: openbao_service_restart | bool

- name: Reload openbao
  become: true
  ansible.builtin.service:
    name: '{{ openbao_systemd_service_name }}'
    state: reloaded
  when: openbao_service_reload | bool
